### PR TITLE
Allow es6 modules

### PR DESCRIPTION
**Pull request by mdedys**
- set modules to true for emcaFeatures

### CODE REVIEW

**Comment by omsmith** [comment]
This isn't covered by the _es6_ env?

**Comment by mdedys** [comment]
No it is not. https://github.com/eslint/eslint/issues/2112

**Comment by dbatiste** [comment]
If you're further curious about which features are supported, etc. they are outlined [here](http://eslint.org/docs/user-guide/configuring.html).

**Comment by dbatiste** [comment]
So I am not sure if we are going to see any new linting errors in other projects as a result.

**Comment by omsmith** [comment]
This should just be allowing more things, so I wouldn't expect any errors

**Comment by dbatiste** [comment]
Yeah.  This used to also enable global-strict, which would have changing linting results.  Looks like that was removed though.

**Pull request merged**
