### PR TITLE
initial configuration for class member sorting

### PR DESCRIPTION
**Pull request by ctwomey1**
This PR was inspired from a comment @m6jones left on my [pr](https://github.com/BrightspaceHypermediaComponents/organizations/pull/76#discussion_r291747845).  I personally find that comments like that end up not being followed consistently unless you codify the rules somewhere.  So hopefully this works for both of you.

Currently this is configured for just one config, but if we're ok with introducing this plugin we can certainly expand it to the other configs.

As an example this was run against BrightspaceHypermediaComponents/organizations and I got the following output:

```
> eslint . --ext .js,.html test/**/*.js test/**/*.html demo/**/*.js demo/**/*.html


C:\d2l\github\organizations\components\d2l-organization-date\d2l-organization-date.js
  26:2  error  Expected static getter template to come before constructor    sort-class-members/sort-class-members
  32:2  error  Expected static getter properties to come before constructor  sort-class-members/sort-class-members
  50:2  error  Expected static getter observers to come before constructor   sort-class-members/sort-class-members
  58:2  error  Expected static getter is to come before constructor          sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-detail-card\d2l-organization-detail-card.js
   27:2  error  Expected static getter template to come before constructor    sort-class-members/sort-class-members
  323:2  error  Expected static getter properties to come before constructor  sort-class-members/sort-class-members
  358:2  error  Expected static getter observers to come before constructor   sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-image\d2l-organization-image.js
  17:2  error  Expected static getter template to come before constructor    sort-class-members/sort-class-members
  23:2  error  Expected static getter properties to come before constructor  sort-class-members/sort-class-members
  50:2  error  Expected static getter observers to come before constructor   sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-info\d2l-organization-info.js
  27:2  error  Expected static getter template to come before constructor    sort-class-members/sort-class-members
  52:2  error  Expected static getter properties to come before constructor  sort-class-members/sort-class-members
  69:2  error  Expected static getter observers to come before constructor   sort-class-members/sort-class-members
  77:2  error  Expected static getter is to come before constructor          sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-name\d2l-organization-name.js
  26:2  error  Expected static getter template to come before constructor    sort-class-members/sort-class-members
  31:2  error  Expected static getter properties to come before constructor  sort-class-members/sort-class-members
  37:2  error  Expected static getter observers to come before constructor   sort-class-members/sort-class-members
  44:2  error  Expected static getter is to come before constructor          sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-updates\d2l-organization-updates.js
   32:2  error  Expected static getter template to come before constructor    sort-class-members/sort-class-members
  143:2  error  Expected static getter properties to come before constructor  sort-class-members/sort-class-members
  181:2  error  Expected static getter observers to come before constructor   sort-class-members/sort-class-members
  188:2  error  Expected static getter is to come before constructor          sort-class-members/sort-class-members

✖ 22 problems (22 errors, 0 warnings)
```

### CODE REVIEW

**Comment by dlockhart** [comment]
Whoa this is super cool, I had no idea you could do such a thing with eslint!

**Comment by m6jones** [comment]
Nice!!

**Comment by svanherk** [comment]
Agreed, very cool!  Would we also want this in the `lit` config?

**Comment by dlockhart** [comment]
Minor bump or major bump? Most places probably reference this using `^`, which means they'd automatically take a minor bump and break.

**Comment by ctwomey1** [comment]
With semver, when you have version 0.x.x and you bump minor it's considered major right?

**Comment by dlockhart** [comment]
Oh yes you're totally correct -- didn't realize this hadn't gone to `1.0.0` yet! Minor will work.

**Comment by svanherk** [comment]
Won't we need to bump everything in BSI anyways though?  If we start using this in the SDK?

**Comment by ctwomey1** [comment]
@svanherk Dev dependencies don't generally get pulled along I think?

**Comment by dlockhart** [comment]
@svanherk: this is actually published to NPM, so the crazy semver range problems we've been having aren't an issue.

**Comment by ctwomey1** [comment]
Played around with some configuration and added it to lit, getting alpha sort is a bit ugly but it looks like it works to me:

```
> eslint . --ext .js,.html test/**/*.js test/**/*.html demo/**/*.js demo/**/*.html


C:\d2l\github\organizations\components\d2l-organization-consortium\d2l-organization-consortium-tabs.js
   20:2  error  Expected static getter is to come before static getter zzzzz                      sort-class-members/sort-class-members
   22:2  error  Expected static getter properties to come before method sneaky                    sort-class-members/sort-class-members
   22:2  error  Expected static getter properties to come before static getter zzzzz              sort-class-members/sort-class-members
   39:2  error  Expected static getter observers to come before static getter zzzzz               sort-class-members/sort-class-members
   39:2  error  Expected static getter observers to come before static getter properties          sort-class-members/sort-class-members
   39:2  error  Expected static getter observers to come before method sneaky                     sort-class-members/sort-class-members
   45:2  error  Expected static getter template to come before static getter zzzzz                sort-class-members/sort-class-members
   45:2  error  Expected static getter template to come before method sneaky                      sort-class-members/sort-class-members
   86:2  error  Expected constructor to come before method sneaky                                 sort-class-members/sort-class-members
  108:2  error  Expected static getter shouldnotbehere to come before method sneaky               sort-class-members/sort-class-members
  108:2  error  Expected static getter shouldnotbehere to come before static getter zzzzz         sort-class-members/sort-class-members
  108:2  error  Expected static getter shouldnotbehere to come before static getter template      sort-class-members/sort-class-members
  108:2  error  Expected static getter shouldnotbehere to come before constructor                 sort-class-members/sort-class-members
  108:2  error  Expected static getter shouldnotbehere to come before method _isSelected          sort-class-members/sort-class-members
  108:2  error  Expected static getter shouldnotbehere to come before method _sortOrder           sort-class-members/sort-class-members
  108:2  error  Expected static getter shouldnotbehere to come before method _onConsortiumChange  sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-date\d2l-organization-date.js
  26:2  error  Expected static getter template to come before constructor                sort-class-members/sort-class-members
  32:2  error  Expected static getter properties to come before constructor              sort-class-members/sort-class-members
  32:2  error  Expected static getter properties to come before static getter template   sort-class-members/sort-class-members
  50:2  error  Expected static getter observers to come before constructor               sort-class-members/sort-class-members
  50:2  error  Expected static getter observers to come before static getter template    sort-class-members/sort-class-members
  50:2  error  Expected static getter observers to come before static getter properties  sort-class-members/sort-class-members
  58:2  error  Expected static getter is to come before constructor                      sort-class-members/sort-class-members
  58:2  error  Expected static getter is to come before static getter template           sort-class-members/sort-class-members
  58:2  error  Expected static getter is to come before static getter properties         sort-class-members/sort-class-members
  58:2  error  Expected static getter is to come before static getter observers          sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-detail-card\d2l-organization-detail-card.js
   27:2  error  Expected static getter template to come before constructor                sort-class-members/sort-class-members
  323:2  error  Expected static getter properties to come before constructor              sort-class-members/sort-class-members
  323:2  error  Expected static getter properties to come before static getter template   sort-class-members/sort-class-members
  358:2  error  Expected static getter observers to come before constructor               sort-class-members/sort-class-members
  358:2  error  Expected static getter observers to come before static getter template    sort-class-members/sort-class-members
  358:2  error  Expected static getter observers to come before static getter properties  sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-image\d2l-organization-image.js
  17:2  error  Expected static getter template to come before constructor                sort-class-members/sort-class-members
  23:2  error  Expected static getter properties to come before constructor              sort-class-members/sort-class-members
  23:2  error  Expected static getter properties to come before static getter template   sort-class-members/sort-class-members
  50:2  error  Expected static getter observers to come before constructor               sort-class-members/sort-class-members
  50:2  error  Expected static getter observers to come before static getter template    sort-class-members/sort-class-members
  50:2  error  Expected static getter observers to come before static getter properties  sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-info\d2l-organization-info.js
  27:2  error  Expected static getter template to come before constructor                sort-class-members/sort-class-members
  52:2  error  Expected static getter properties to come before constructor              sort-class-members/sort-class-members
  52:2  error  Expected static getter properties to come before static getter template   sort-class-members/sort-class-members
  69:2  error  Expected static getter observers to come before constructor               sort-class-members/sort-class-members
  69:2  error  Expected static getter observers to come before static getter template    sort-class-members/sort-class-members
  69:2  error  Expected static getter observers to come before static getter properties  sort-class-members/sort-class-members
  77:2  error  Expected static getter is to come before constructor                      sort-class-members/sort-class-members
  77:2  error  Expected static getter is to come before static getter template           sort-class-members/sort-class-members
  77:2  error  Expected static getter is to come before static getter properties         sort-class-members/sort-class-members
  77:2  error  Expected static getter is to come before static getter observers          sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-name\d2l-organization-name.js
  26:2  error  Expected static getter template to come before constructor                sort-class-members/sort-class-members
  31:2  error  Expected static getter properties to come before constructor              sort-class-members/sort-class-members
  31:2  error  Expected static getter properties to come before static getter template   sort-class-members/sort-class-members
  37:2  error  Expected static getter observers to come before constructor               sort-class-members/sort-class-members
  37:2  error  Expected static getter observers to come before static getter template    sort-class-members/sort-class-members
  37:2  error  Expected static getter observers to come before static getter properties  sort-class-members/sort-class-members
  44:2  error  Expected static getter is to come before constructor                      sort-class-members/sort-class-members
  44:2  error  Expected static getter is to come before static getter template           sort-class-members/sort-class-members
  44:2  error  Expected static getter is to come before static getter properties         sort-class-members/sort-class-members
  44:2  error  Expected static getter is to come before static getter observers          sort-class-members/sort-class-members

C:\d2l\github\organizations\components\d2l-organization-updates\d2l-organization-updates.js
   32:2  error  Expected static getter template to come before constructor                sort-class-members/sort-class-members
  143:2  error  Expected static getter properties to come before constructor              sort-class-members/sort-class-members
  143:2  error  Expected static getter properties to come before static getter template   sort-class-members/sort-class-members
  181:2  error  Expected static getter observers to come before constructor               sort-class-members/sort-class-members
  181:2  error  Expected static getter observers to come before static getter template    sort-class-members/sort-class-members
  181:2  error  Expected static getter observers to come before static getter properties  sort-class-members/sort-class-members
  188:2  error  Expected static getter is to come before constructor                      sort-class-members/sort-class-members
  188:2  error  Expected static getter is to come before static getter template           sort-class-members/sort-class-members
  188:2  error  Expected static getter is to come before static getter properties         sort-class-members/sort-class-members
  188:2  error  Expected static getter is to come before static getter observers          sort-class-members/sort-class-members

✖ 68 problems (68 errors, 0 warnings)
```

**Comment by dbatiste** [comment]
Are we sure we want the peer dependency?  I think all installers would be required to include the plugin as a dependency, even if the config they are using does not require it.  The React plugin was the one we previously removed from peer dependencies, and later, we chose not to add the html plugin.

**Comment by ctwomey1** [comment]
@dbatiste i removed the peer as per your feedback in https://github.com/Brightspace/eslint-config-brightspace/pull/22/commits/240d1b2ef21930f29e304ea12ba114d2170aef9a

**Comment by dbatiste** [comment]
Thanks Chester.  Missed that.  :)

**Pull request merged**
